### ISSUE TITLE
GPS Tracker Type

### ISSUE THREAD

**Issue by dafinoer** [mattdsteele/spot-tracker-tracker#7]
What type of GPS Tracker are you using?

**Comment by mattdsteele** [comment]
Hi! I'm using a SPOT Tracker, generation 3. It's not for sale anymore, but I picked up a cheap used one and was able to activate it without issue. https://www.findmespot.com/en-ca/products-services/spot-gen3

There's a 4th generation device for sale and currently supported. I don't have much experience with it, but I'd expect it would work the same way; All SPOT devices can be configured to expose a JSON endpoint with the most recent pings, which is how I'm extracting the data and sending it to AWS Location services.

You can see a full writeup of the architecture at https://steele.blue/serverless-bike-gps/ if you're curious.

The other popular device in this space is made by Garmin (the inReach). I don't have any experience with it, but there may be similar integration points to extract data from Garmin's ecosystem and into a tool of your choice.

Let me know if you have any other questions. Thanks!
